### ISSUE TITLE
这个扩展是修改了原候选的样式还是使用了新面板替换了原候选栏？

### ISSUE THREAD

**Issue by yueduz** [tuberry/ibus-tweaker#10]
这个扩展是修改了原候选的样式还是使用了新面板替换了原候选栏？
 能不能通过css为候选栏添加淡入淡出动画？

**Comment by yueduz** [comment]
我想编写gnome-shell插件，但是找不到手册。不知道有哪些可用对象，不知道哪些对象都有什么功能。

**Comment by tuberry** [comment]
> 这个扩展是修改了原候选的样式还是使用了新面板替换了原候选栏？

前者
> 能不能通过css为候选栏添加淡入淡出动画？

不知道

> 我想编写gnome-shell插件，但是找不到手册。不知道有哪些可用对象，不知道哪些对象都有什么功能。

善用搜索
