### ISSUE TITLE
compatibility with gnome 40

### ISSUE THREAD

**Issue by bpint** [tuberry/ibus-tweaker#11]
It seems ibus-tweaker 28 does not work on newly released gnome 40. when will there be a new version?

**Comment by tuberry** [comment]
Most of my extensions should work on Gnome Shell 40 except their prefs pages. And it will take some time to port them to Gtk4. The new version would be released in 1 or 2 days after the gnome-shell-40 is available in Archlinux's testing repo.

**Comment by bpint** [comment]
by the way, i created packages on AUR,

**Comment by tuberry** [comment]
>By the way, i created packages on AUR,

Thanks.

>  However, i do not know how to match the extension versions to gnome-shell versions. I will investigate more.

The supported Gnome version is defined in [metadata.json](https://github.com/tuberry/ibus-tweaker/blob/a63591eb37c98c40272a94c46397ab87428a2725/ibus-tweaker%40tuberry.github.com/metadata.json#L7), but it should be fine to use the latest version in Archlinux.

> Will the extension for gnome40 be backward compatible?

Nope, I've tagged the final version for GNOME3.38.
