### ISSUE TITLE
能否增加一个功能，原本在 ibus-setup 里的 “在应用程序窗口中启用内嵌编辑模式” 勾选开关？

### ISSUE THREAD

**Issue by YQ-YSY** [tuberry/ibus-tweaker#13]
很多网友在使用 ibus-pinyin 时，都遇到过一个很严重的问题：
在 FireFox 游览器的输入框中，Ctrl + A 或移动光标选择文本时，文本会被删除。
后来发现解决方法是：
在终端输入 ibus-setup 打开 ibus首选项，在常规设置中，
取消默认已勾选的“在应用程序窗口中启用内嵌编辑模式”，问题就能解决。
https://forum.ubuntu.org.cn/viewtopic.php?p=3225704#p3225704

但不幸的是，这个方法只在 Gnome2 和 Xfce4 上管用，在 Gnome3 上不管用。
所以很希望能在 ibus-tweaker 中增加 “在应用程序窗口中启用内嵌编辑模式” 勾选开关的功能，
让  ibus-pinyin  死而复生。

——————————

我听说你也参与开发 ibus-libpinyin ，我是在 Ubuntu 中文论坛得知这一消息的：
https://forum.ubuntu.org.cn/viewtopic.php?p=3225743#p3225743
论坛中的 Ping-Wu （长辈，美籍华裔）很青睐  ibus-libpinyin ，也对  ibus-pinyin 赞赏有加，
两者的优缺点他都十分熟悉，曾经在论坛里多次谈起对 Linux 拼音输入法的看法。

而我，是因为使用 ibus-Rime 来实现我的“单手笔顺输入法”，所以用到了 ibus-tweaker 。
单手笔顺输入法（2.0版） https://github.com/YQ-YSY/one-hand_Rime
现在的拼音输入法，造成了网络上出现很多“谐音自创词、谐音恶搞词”，这对正常的语言环境是极大的伤害。
有木有酱紫？
我的“单手笔顺输入法”，用数字输入，3万汉字，每个字最多6码即可打出，常用字1~5码即可打出，
重码极少，词组的输入速度更快——这是“笔顺输入法”的先天优势，每个汉字都不一样嘛。

可惜 ibus-table 在支持“用数字小键盘输入代码（不是用来选字）”方面有缺陷，总是自动多了一个回车。
要不然， ibus-table 的“星号模糊匹配”功能就恰好弥补  ibus-Rime 的不足，能成倍提高输入速度。
单手笔顺输入法（ibus-table实验版） https://forum.ubuntu.org.cn/viewtopic.php?f=35&t=488891

其实我的野心是：让拼音和笔顺两种输入法同时使用，不用切换，成为互补关系，大大提高汉字输入效率。
用户不记得拼音时，就输入笔顺；
用户不记得笔顺时，就输入拼音。
但我不是程序员，不会写程序，空有梦想，而无法实现（也没钱聘请程序员）。

所以只能寄希望于“某一天，会有某个程序员，对此感兴趣”，或全新开发、或改进旧版、或增补功能，都好。
如果你很忙，那也没关系。
人生不如意事十之八九，（改变命运是有办法的，但在“其力末充”之前）我继续等待就是了。

**Comment by tuberry** [comment]
> 很多网友在使用 ibus-pinyin 时，都遇到过一个很严重的问题：

我不用 ibus-pinyin， 但看了一眼这个问题应该已在上游修复了https://github.com/ibus/ibus-pinyin/commit/d60f1fec76be9000e02956f30bf86237e4b83f47 ，所以将 ibus-pinyin 更新到 git 最新提交应该就没问题了。

> 我听说你也参与开发 ibus-libpinyin ，我是在 Ubuntu 中文论坛得知这一消息的：

惭愧，我并未参与 ibus-libpinyin 开发，目前为止只是提了些问题并没有做过什么贡献。

> 而我，是因为使用 ibus-Rime 来实现我的“单手笔顺输入法” 。

恭喜。

> 现在的拼音输入法，造成了网络上出现很多“谐音自创词、谐音恶搞词”，这对正常的语言环境是极大的伤害。

谐音存在于古今中外的语言中，网络也不算那么正式的辞令场合，不必如此介怀。
