### ISSUE TITLE
关于@shenlebantongying的言论

### ISSUE THREAD

**Issue by HollowMan6** [tuberry/ibus-tweaker#16]
您好！这是我对@shenlebantongying的言论进行的一个正式的回复，所有的对他的言论的解释说明都包含在这里面了。

https://github.com/HollowMan6/Customize-IBus/issues/5

实在抱歉，因为@tuberry 您没有在GitHub主页留下邮箱，所以之前一部分使用了您的项目时未能及时联系到您。我在接手 https://github.com/openSUSE/mentoring/issues/158 项目时没有过任何GNOME-Shell扩展编程的经验，是您的项目带领我入了门。

除了利用了此项目的部分代码，他说我还直接抄袭了另外的项目，这是纯粹的诽谤，其他的功能都是我自己独立编写完成的。因而我对@shenlebantongying的言论无法接受。

我猜测是不是@shenlebantongying也申请GSoC项目了，然后落选，遂来这里造我的谣，挑我的刺。（仅为个人猜测）他这话说的完全没根据，我都不知道他为啥这么说。最关键问题我以前都没跟他有过接触，他就把我屏蔽了，为什么要屏蔽我参与讨论？是不是心里有鬼？所以基本肯定他是故意造我谣。另外修改这么多次，为什么要特地把修改历史删了？是不是在组织诽谤我的逻辑？

![-40c410ee1b347449](https://user-images.githubusercontent.com/43995067/118960487-ec42d280-b995-11eb-894d-58c0cd41dcc0.jpg)

我相信群众的眼睛是雪亮的，大家应该通过我的解释明白谁是谁非。

谢谢！

**Comment by HollowMan6** [comment]
我咨询了GitHub，如果您认可我的说法，请您将此issue和https://github.com/tuberry/ibus-tweaker/issues/15 一并删除，来恢复我的名誉。我也会将此Issue删除: https://github.com/HollowMan6/Customize-IBus/issues/5 如需进一步讨论请联系我的邮箱 hollowman@hollowman.ml 或另开issue，谢谢！

![Screenshot_20210520_174312_com tencent androidqqmail](https://user-images.githubusercontent.com/43995067/118963154-bfdc8580-b998-11eb-9f5a-1a52f3214306.jpg)

**Comment by tuberry** [comment]
#15 在我看来是告诉我有这样一个优秀的项目存在可以借鉴一些功能，我的回复主要说了说观感但也没有否定别人的需求，现在看来不值一哂，有不对的地方你多担待。此外，我向来是不吝以最好的善意来看待他人的，更何况是为本项目贡献的人。再者正如GPL许可证所述，我不关心别人用本项目做什么，你也没有必要告诉我，当然还是感谢你对本项目的关注。:)
我认为完全没有小事化大的必要。你要求我依据我的看法来删除该议题，我的看法是我有权限但没有权力。你提到了“诽谤”，如果依此行事等于我认定其诽谤，但抱歉我不通法律不敢擅专。所以如果你能提供相关法律证明材料（邮箱：orzun@foxmail.com）或者当事人 @shenlebantongying 主动要求删除，我将立即删除。谢谢。

**Comment by HollowMan6** [comment]
您好！谢谢您的回复。当时写 https://github.com/HollowMan6/Customize-IBus/issues/5 回复时正好在@shenlebantongying 气头上，如果有冒犯的地方请多多包含。

> #15 在我看来是告诉我有这样一个优秀的项目存在可以借鉴一些功能。

我觉得您应该是忽略了他的一些意思。他说：
> He simply copy a few projects into one, so that he can put another "project" on his résumé.

> "rearrange a few buttons, then it is MY project" kind of shits (like many made-in-china "open source" or pirated software which are just renaming open source projects with little alternation. 

> It is still the same software but with some customization copied from some other projects

说得是我的所有功能都是抄袭拼凑的。这是对我的努力成果的亵渎。除了您的项目中包含的功能，其他的功能都是我一个字符一个字符辛苦码出来的，我不能忍受别人对我的成果的亵渎，同时我也将其认作为是对我的诽谤。

> (and renaming variables to increase "commit number" and SLOC like his other projects).

这句话说我通过重命名一些变量名，来达到增加 贡献数 的目的，顺便还把我的其他项目侮辱了一番，却不给出实际证据，比如说我的哪个项目，哪个commit是重命名一些变量名，来达到增加 贡献数 的目的了？

因而我认为这是对我恶毒的攻击。然而他似乎并不能为自己的言论负责，我还没有作出任何回复他就把我拉进了黑名单。我在写那篇回应的同时也通过他的邮箱发送邮件 shenlebantongying@gmail.com 向他讨个说法，但是截至目前他依然没回复我。

> 我认为完全没有小事化大的必要。你要求我依据我的看法来删除该议题，我的看法是我有权限但没有权力。你提到了“诽谤”，如果依此行事等于我认定其诽谤，但抱歉我不通法律不敢擅专。所以如果你能提供相关法律证明材料（邮箱：[orzun@foxmail.com](mailto:orzun@foxmail.com)）或者当事人 @shenlebantongying 主动要求删除，我将立即删除。谢谢。

我确实没有小事化大的想法。如果您想要确保 @shenlebantongying 言论自由的权利，请也同时确保一下我的言论自由。因为目前@shenlebantongying 将我屏蔽了，我没有办法在#15 下回复。因而请您在 #15 下帮我回复一下以下内容，来确保后来者能够了解到事情的原委。

```
@HollowMan6 has a reply to you. But you blocked him, so he can't make any comments with this issue. You can unblock him and discuss with him by going to this issue:

https://github.com/HollowMan6/Customize-IBus/issues/5

```

您在发完上述评论后就可以把这个Issue关了。谢谢！您的项目真的很棒！

**Comment by tuberry** [comment]
你说的不无道理。其言论或有夹带私货，我滤去其中与此项目无关的部分以保证讨论不会离题。对我的做法给你造成的困扰深感抱歉。总之，我已经向作者征得同意删除了该议题。

![reply](https://user-images.githubusercontent.com/17917040/119208747-1ac7c700-bad6-11eb-9b8f-841534f9980b.png)

此议题也将即刻删除。谢谢。 :)
