### ISSUE TITLE
可否添加功能使 候选词窗口不跟随光标移动

### ISSUE THREAD

**Issue by yuw0360** [tuberry/ibus-tweaker#19]
ibus-rime候选词窗口在libreoffice等应用随光标一直移动，〖在firefox却没有这个情况（固定在第一个打出的字母处）〗，可否添加功能使 候选词窗口不跟随光标移动
![Screenshot from 2021-06-24 20-13-51](https://user-images.githubusercontent.com/83384685/123261055-ddb58100-d528-11eb-8c27-7abc3b301dd0.png)
![Screenshot from 2021-06-24 20-14-15](https://user-images.githubusercontent.com/83384685/123261062-df7f4480-d528-11eb-989d-cc179326b722.png)

**Comment by tuberry** [comment]
这个我给上游提过[PR](https://github.com/rime/ibus-rime/pull/102)，最后作者自己弄了[选项](https://github.com/rime/ibus-rime/commit/cfa7bce2492762e3baf4775518ddc0a1dd90e3c0)。具体来说，你应该在`~/.config/ibus/rime/build/ibus_rime.yaml`中添加一项：
```yaml
style:
  cursor_type: select
```
然后再部署什么的。如果这样没奏效请直接报告给上游。
