### ISSUE TITLE
emacs不能弹出中文

### ISSUE THREAD

**Issue by cnglen** [tuberry/ibus-tweaker#2]
如果用了这个插件， emacs不能输入中文。

能不能支持下？

**Comment by tuberry** [comment]
我 emacs 用的不多，但这应该不是插件的问题：
（Arch / Gnome shell 3.36.2 / Emacs 26.3 / IBus 1.5.22-1 / ibus-libpinyin 1.11.1-3 / ibus-rime 1.4.0-2）
![image](https://user-images.githubusercontent.com/17917040/81495132-a530f480-92e0-11ea-93f3-7e7cd7ac0682.png)

你排查一下是不是环境变量或配置文件的影响。
