### ISSUE TITLE
Wayland中窗口底部会被候选词遮挡

### ISSUE THREAD

**Issue by Xiaoyang-Lyu** [tuberry/ibus-tweaker#24]
### 描述
在wayland里如果在telegram窗口的底部输入会出现如下图的情况  
https://img1.imgtp.com/2023/07/16/bvGwlQ3D.png
在xrog的telegram就不会出现这个问题  

如果关闭在关闭了ibus-tweak拓展，再在telegram窗口底部输入，明显候选词框避开了输入词

**Comment by tuberry** [comment]
在 Gnome 44.1 / Telegram 4.8.4 / Wayland 下无法复现。

![sc001](https://github.com/tuberry/ibus-tweaker/assets/17917040/cda92138-6c3c-4a1d-8b8b-cd4ad6d214b2)
