### ISSUE TITLE
可否通过 css 的方式修正 / 美化默认的选字框

### ISSUE THREAD

**Issue by plumlis** [tuberry/ibus-tweaker#25]
类似 kimpanel 插件的这样

https://github.com/wengxt/gnome-shell-extension-kimpanel/pull/71

ibus 的默认选字框也存在一些细节上的美化问题。

**Comment by tuberry** [comment]
可以。

你可以参照[这里](https://wiki.archlinuxcn.org/wiki/IBus#%E4%BF%AE%E6%94%B9_Gnome-shell_%E4%B8%AD_ibus_%E5%80%99%E9%80%89%E6%A1%86%E7%9A%84%E5%AD%97%E4%BD%93%E5%92%8C%E5%AD%97%E5%8F%B7)以及上游代码中的[style_class](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/ibusCandidatePopup.js?ref_type=heads)([简化版](https://github.com/tuberry/ibus-tweaker/blob/66853f582815e06d76f951ff134fff9a63ebfd44/src/extension.js#L63-L84))和 [scss](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/data/theme/gnome-shell-sass/widgets/_ibus-popup.scss?ref_type=heads) 修改 IBus 的样式。当然我更推荐使用[user-theme-x](https://github.com/tuberry/user-theme-x)独立于主题修改。

**Comment by plumlis** [comment]
感谢你的回复，已经通过修改css的方式实现了想要的效果。不过还是想吐槽 ibus 的各种跳键和空格自动输入的bug真的很烦人。

-------

顺便冒昧的问一个不相关的问题：
Simple Subscriber
这个插件还有机会更新到 Gnome 45 版本吗？
谢谢。

**Comment by tuberry** [comment]
> 不过还是想吐槽 ibus 的各种跳键和空格自动输入的bug真的很烦人。

建议向 IBus 报告，开发者也许知道怎么回事。:)

> Simple Subscriber
这个插件还有机会更新到 Gnome 45 版本吗？

实在抱歉，我不再维护它了，更新了项目描述。 :(
> Sorry to the few users, this project is no longer maintained for inactive dependencies and limited use cases. :( 

展开来说：
其一，[SSD 订阅协议](https://github.com/TheCGDF/SSD-Windows/wiki/HTTP-Subscription-Agreement)没了，[ss-libev](https://github.com/shadowsocks/shadowsocks-libev) 目前 Bug-fix-only。
其二，此扩展仅更新订阅，比理想的 GUI 功能差得太多（正如其名只能作为补充），也不是实现这些功能的正确途径。至于 Gnome [系统代理](https://wiki.gnome.org/Projects/NetworkManager/Proxies)一直不甚理想，而此扩展起的用户进程也不便配合 iptables/nftables 工作。
总之蛮鸡肋的，建议改用支持更完善（更适合用例）的代理应用。

**Comment by tuberry** [comment]
不客气。:)
