### ISSUE TITLE
字体设置能否用列表

### ISSUE THREAD

**Issue by CrotchBurnt** [tuberry/ibus-tweaker#26]
类似VSCode的配置里的`"editor.fontFamily": "'PingFang SC', '更纱黑体 SC'"`
方便设置字体回退

**Comment by tuberry** [comment]
GTK 字体按钮只能处理单个字体但基本够用，而且我觉得应该尽量少用文本框，所以暂不考虑效仿 VSCode。:(

建议尝试配置 [fontconfig](https://wiki.archlinux.org/title/Font_configuration) 看看，不行的话可以参考[这里](https://github.com/tuberry/ibus-tweaker/issues/25#issuecomment-1748166780) 用 CSS 实现。
