### ISSUE TITLE
Error in Gnome 46 , ibus-tweaker verion 45

### ISSUE THREAD

**Issue by wagafo** [tuberry/ibus-tweaker#27]
Ubuntu 24.04
Gnome 46
ibus-tweaker version 45

The extension cannot be enabled, it gives the following error:

`
Error: Requiring Json, version none: Typelib file for namespace 'Json' (any version) not found

Stack trace:
  require@resource:///org/gnome/gjs/modules/esm/gi.js:16:28
  @gi://Json/:3:25
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  `

**Comment by wagafo** [comment]
Solved by installing the  library:

sudo apt install libjson-c-dev

**Comment by tuberry** [comment]
I'm fairly sure it should be [libjson-glib](https://packages.debian.org/sid/libjson-glib-1.0-0), one of the [gnome-shell](https://packages.debian.org/experimental/gnome-shell) dependencies so that this problem shouldn't be happening.

Maybe you can report it to Ubuntu. :)

**Comment by tuberry** [comment]
The dependency on `json-glib` was dropped in the latest commit, you can try to install the extension from [Github](https://github.com/tuberry/ibus-tweaker?tab=readme-ov-file#manual) and uninstall the JSON package you installed then re-login to see if it works. :)
