### ISSUE TITLE
自定义字体字号不影响序号

### ISSUE THREAD

**Issue by yueduz** [tuberry/ibus-tweaker#3]
![2020-07-03 05-27-53 的屏幕截图](https://user-images.githubusercontent.com/1448159/86410786-04622280-bcee-11ea-8495-e9637602b6f8.png)

**Comment by tuberry** [comment]
这个是我偷了点懒，修了。你可以等更新或者从 github 安装
![image](https://user-images.githubusercontent.com/17917040/86461126-17134080-bd5c-11ea-9d62-6ffb1f5b8551.png)
