### ISSUE TITLE
After upgrade, ubuntu 20.04 cannot be used

### ISSUE THREAD

**Issue by Hoking007** [tuberry/ibus-tweaker#4]
After upgrade, ubuntu 20.04 cannot be used

**Comment by tuberry** [comment]
Sorry, I don't have an Ubuntu now and it works on gnome-shell 3.36.4.
Could you please provide some logs and screenshots for debugging?

**Comment by Hoking007** [comment]
![image](https://user-images.githubusercontent.com/55968385/87400732-c1585700-c5eb-11ea-9c88-28fd22c5b3e4.png)
![image](https://user-images.githubusercontent.com/55968385/87400805-dd5bf880-c5eb-11ea-879f-bb1baae2211b.png)
When I click on upgrade, it becomes as shown in the screenshot and becomes unavailable. I don't know how to crawl the log, how can I do it?

**Comment by tuberry** [comment]
1. press <kbd>Alt</kbd>+<kbd>F2</kbd> and input `lg`, then press <kbd>Enter</kbd>. Click `Extension -> IBus Tweaker -> Show Errors`, or:
2. install `gnome-logs` and search `ibus-tweaker` in `All` tab:
![image](https://user-images.githubusercontent.com/17917040/87402449-2b71fb80-c5ee-11ea-92bb-34d67b9b3609.png)

**Comment by Hoking007** [comment]
JS ERROR: Extension ibus-tweaker@tuberry.github.com: Error: A different version was loaded previously. You need to log out for changes to take effect.
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:341:52
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:232:39
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13
===============================================

After logging out, it is normal, thank you very much!
：）
