### ISSUE TITLE
在光标位置跟随图标以输入法状态，通过扩展有没有可能实现?

### ISSUE THREAD

**Issue by yueduz** [tuberry/ibus-tweaker#5]
![2020-09-07 09-26-01 的屏幕截图](https://user-images.githubusercontent.com/1448159/92340379-a76b5a00-f0ec-11ea-8fc4-6a35e2911b78.png)
像这样，如果大小写锁定打开在光标上跟随一个黄点，如果是英文输入法在光标下方跟随一个绿点。
中文输入法什么也不跟，跟了可能和候选条冲突。

在没有开始输入，文本框光标刚被激活时就出现跟随图标。

**Comment by tuberry** [comment]
光标是应用画的，我不知道如何得到它的位置更遑论那两个点了
