### ISSUE TITLE
能不能记住上次退出时输入状态

### ISSUE THREAD

**Issue by yueduz** [tuberry/ibus-tweaker#9]
我看到有一个功能能设置首次启动时是中是英。能不能更进一步记住程序上次退出时的中英状态，在下次启动时恢复呢？

**Comment by tuberry** [comment]
你从 github 安装看行不行。

**Comment by yueduz** [comment]
不行

tuberry <notifications@github.com> 于2020年10月21日周三 上午12:05写道：

**Comment by tuberry** [comment]
请具体说明在哪不行如何不行。仅仅是“不行”对我来说毫无意义。

**Comment by yueduz** [comment]
![2020-10-25 11-30-48 的屏幕截图](https://user-images.githubusercontent.com/1448159/97098268-f7f74080-16b5-11eb-8bd7-cd6d82c063f0.png)
扩展无法启用

**Comment by tuberry** [comment]
安装时执行 `cd ibus-tweaker && make install` 会编译 [gschemas](https://github.com/tuberry/ibus-tweaker/blob/53f554bba095605203919f11d8db948c95bf8502/Makefile#L54) 。能发一下安装时的输出吗？

**Comment by yueduz** [comment]
[image: 2020-10-27 09-59-00 的屏幕截图.png]
开始我没有使用make安装直接复制了文件夹，所以有错误，使用make安装后没有错误提示，但是不能记住状态。

tuberry <notifications@github.com> 于2020年10月25日周日 上午11:49写道：

**Comment by tuberry** [comment]
ibus-libpinyin / ibus-rime 无法复现。

**Comment by yueduz** [comment]
![2020-10-29 10-49-36 的屏幕截图](https://user-images.githubusercontent.com/1448159/97520346-f4c1c480-19d5-11eb-937b-41ee3540ef95.png)
我使用make安装，也重启了系统，还是不能记住状态。我打开gedit切换到中文，关闭gedit，再打开gedit，还是默认英文。我不知道从哪里可以找到日志。

**Comment by tuberry** [comment]
用的什么输入法？

**Comment by yueduz** [comment]
ibus-rime

**Comment by tuberry** [comment]
这不合理啊，
1. 你用的输入方案英文状态指示显示的是什么?
2. 安装 `gnome-logs` 在全部搜索 ibus-tweaker 看看有没有结果。

**Comment by yueduz** [comment]
![2020-11-01 12-31-07 的屏幕截图](https://user-images.githubusercontent.com/1448159/97795202-5a17ee80-1c3e-11eb-81de-45245e9c4bf5.png)
 gnome-logs 里搜索什么也没有

**Comment by tuberry** [comment]
这个插件记住的是一个输入法的中英文状态（按 Shift 切换），而不是你上次用的什么输入法。
